const fs=require('fs');
const p='tools/render_nidom_j1_variative_v22.js';
let s=fs.readFileSync(p,'utf8');
if(!s.includes('V27_KAMUS_HADITH')){
 s=s.replace('</style>',`\n/* V27_KAMUS_HADITH */\n.v27-kamus{margin-top:3.5mm;padding:3.2mm 4mm;border-top:.35mm solid #c9c2a8;border-bottom:.35mm solid #c9c2a8;background:#faf8f1}.v27-kamus h3{margin:0 0 2.5mm;font-size:7.6pt;letter-spacing:.09em;color:#405d49}.v27-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:2.5mm}.v27-word{text-align:center;padding:2.2mm 1.5mm;border:.22mm solid #ded8c7;border-radius:2mm;background:#fff;min-height:18mm}.v27-ar{font-family:'UthmanTaha','KFGQPC Uthman Taha Naskh','Traditional Arabic',serif;font-size:16pt;line-height:1.35;direction:rtl;margin-bottom:1.2mm}.v27-id{font-size:7pt;line-height:1.3;color:#4f5650}.v27-src{margin-top:1.8mm;font-size:6.3pt;color:#7a7e77;text-align:right}\n</style>`);
 const marker='const check=await pg.evaluate';
 const inject=`await pg.evaluate(()=>{\n const root=document.querySelector('.page');if(!root||root.querySelector('.v27-kamus'))return;\n const pageNo=parseInt((document.querySelector('.num')?.textContent||'0'),10)||0;\n const dict={\n  salam:[['أَفْشُوا','sebarkanlah'],['السَّلَامَ','salam'],['بَيْنَكُمْ','di antara kalian']],\n  baik:[['فَلْيَقُلْ','maka hendaklah berkata'],['خَيْرًا','yang baik'],['أَوْ','atau'],['لِيَصْمُتْ','hendaklah diam']],\n  marah:[['لَيْسَ','bukan'],['الشَّدِيدُ','orang yang kuat'],['يَمْلِكُ','menguasai / mengendalikan'],['نَفْسَهُ','dirinya'],['عِنْدَ','ketika'],['الْغَضَبِ','marah']],\n  jujur:[['إِنَّ','sesungguhnya'],['الصِّدْقَ','kejujuran'],['يَهْدِي','menuntun'],['إِلَى','kepada'],['الْبِرِّ','kebaikan']],\n  kasih:[['مَنْ','siapa'],['لَا','tidak'],['يَرْحَمِ','menyayangi'],['النَّاسَ','manusia'],['يَرْحَمْهُ','menyayanginya'],['اللهُ','Allah']],\n  amanah:[['وَإِذَا','dan apabila'],['اؤْتُمِنَ','diberi amanah'],['خَانَ','ia berkhianat']],\n  hormat:[['لَيْسَ','bukan'],['مِنَّا','dari golongan kami'],['يَرْحَمْ','menyayangi'],['صَغِيرَنَا','yang muda di antara kami'],['يُوَقِّرْ','menghormati'],['كَبِيرَنَا','yang tua di antara kami']],\n  tolong:[['وَاللهُ','dan Allah'],['فِي','dalam'],['عَوْنِ','pertolongan'],['الْعَبْدِ','hamba'],['أَخِيهِ','saudaranya']]\n };\n const ranges=[[1,4,'salam'],[5,8,'baik'],[9,13,'marah'],[14,18,'jujur'],[21,24,'kasih'],[25,28,'amanah'],[29,32,'hormat'],[33,35,'tolong']];\n let theme=(ranges.find(r=>pageNo>=r[0]&&pageNo<=r[1])||[])[2];\n if(!theme){const prior=pageNo<=20?'jujur':pageNo<=36?'tolong':'tolong';theme=prior;}\n let words=dict[theme]||dict.salam;\n // Rotate vocabulary across repeated pages so the dictionary itself also progresses.\n const offset=Math.max(0,pageNo-1)%words.length;words=[...words.slice(offset),...words.slice(0,offset)].slice(0,Math.min(4,words.length));\n const box=document.createElement('section');box.className='v27-kamus';box.innerHTML='<h3>KAMUS HADITS · ARTI PER KATA</h3><div class="v27-grid">'+words.map(w=>'<div class="v27-word"><div class="v27-ar">'+w[0]+'</div><div class="v27-id">'+w[1]+'</div></div>').join('')+'</div><div class="v27-src">Baca bersama guru · makna disederhanakan sesuai tingkat Jilid 1</div>';\n const sig=root.querySelector('.sign'),foot=root.querySelector('.footer');if(sig)root.insertBefore(box,sig);else if(foot)root.insertBefore(box,foot);else root.appendChild(box);\n});`;
 if(s.includes(marker))s=s.replace(marker,inject+marker);else throw new Error('V27_INSERTION_POINT_MISSING');
 fs.writeFileSync(p,s);
}
console.log('V27_KAMUS_HADITH=PATCHED');