const fs=require('fs');
const p='tools/render_nidom_j1_variative_v22.js';
let s=fs.readFileSync(p,'utf8');
if(!s.includes('V26_CONTENT_ENRICHED')){
 s=s.replace('</style>',`\n/* V26_CONTENT_ENRICHED — baseline v2.3 geometry, add real pedagogical content only */\n.v26-enrich{margin-top:4mm;padding:4mm 4.5mm;border:.28mm solid #d8d2bd;border-radius:3mm;background:#fbfaf6}.v26-enrich h3{margin:0 0 2.6mm;font-size:8pt;letter-spacing:.07em;color:#405d49}.v26-enrich p,.v26-enrich li{font-size:8.2pt;line-height:1.55}.v26-enrich ul{margin:0;padding-left:5mm}.v26-grid{display:grid;grid-template-columns:1fr 1fr;gap:3mm}.v26-card{padding:3mm;border:.25mm solid #dedbd0;border-radius:2mm;background:#fff}.v26-answer{height:6mm;border-bottom:.22mm solid #d4d5cf;margin-top:1.5mm}.v26-mini{font-size:7.4pt;color:#6e756e}\n</style>`);
 const marker='const check=await pg.evaluate';
 const inject=`await pg.evaluate(()=>{\n const root=document.querySelector('.page');if(!root||root.querySelector('.v26-enrich'))return;\n const pageNo=parseInt((document.querySelector('.num')?.textContent||'0'),10)||0;if(pageNo>=39)return;\n const h=root.getBoundingClientRect().height;let max=0;[...root.children].forEach(e=>{const r=e.getBoundingClientRect();max=Math.max(max,r.bottom-root.getBoundingClientRect().top)});const free=h-max;\n // Only enrich pages that are genuinely sparse. Do not stretch existing layout.\n if(free<150)return;\n const txt=(document.body.innerText||'').toLowerCase();const box=document.createElement('section');box.className='v26-enrich';\n let title='INGAT & LAKUKAN';let body='<div class="v26-grid"><div class="v26-card"><b>Ingat kembali</b><p>Sebutkan satu akhlak baik dari pertemuan sebelumnya.</p><div class="v26-answer"></div></div><div class="v26-card"><b>Aksi hari ini</b><p>Pilih satu perbuatan kecil yang akan kamu praktikkan.</p><div class="v26-answer"></div></div></div>';\n if(txt.includes('hadits')||txt.includes('hadis')){title='DARI HADITS KE PERBUATAN';body='<div class="v26-grid"><div class="v26-card"><b>Contoh</b><p>Ceritakan satu keadaan sederhana ketika pesan hadits ini bisa kamu lakukan.</p><div class="v26-answer"></div></div><div class="v26-card"><b>Bukan contoh</b><p>Sebutkan satu sikap yang berlawanan dengan pesan hadits.</p><div class="v26-answer"></div></div></div>';}\n if(txt.includes('kisah')||txt.includes('ilustrasi')){title='AKU MEMAHAMI KISAH';body='<ul><li>Siapa yang menunjukkan akhlak baik?</li><li>Apa keputusan yang seharusnya diambil?</li><li>Apa yang mungkin terjadi jika memilih sikap sebaliknya?</li></ul><div class="v26-answer"></div><div class="v26-answer"></div>';}\n else if(txt.includes('kasus')||txt.includes('pilih')){title='COBA KASUS BARU';body='<p>Bayangkan hal yang sama terjadi di rumah atau di kelas. Apa tindakan pertamamu? Jelaskan dengan kalimat sederhana.</p><div class="v26-answer"></div><div class="v26-answer"></div>';}\n else if(txt.includes('praktik')||txt.includes('role')){title='PRAKTIK SEKALI LAGI';body='<div class="v26-grid"><div class="v26-card"><b>Dengan teman</b><p>Praktikkan situasinya bergantian.</p></div><div class="v26-card"><b>Di rumah</b><p>Ulangi satu kali dan ceritakan hasilnya kepada orang tua.</p></div></div><p class="v26-mini">Guru/orang tua cukup memberi tanda setelah praktik terlihat.</p>';}\n else if(txt.includes('evaluasi')||txt.includes('quiz')){title='SATU LANGKAH LEBIH DALAM';body='<p>Pilih satu jawaban yang menurutmu paling penting. Mengapa sikap itu baik? Beri satu contoh nyata.</p><div class="v26-answer"></div><div class="v26-answer"></div>';}\n box.innerHTML='<h3>'+title+'</h3>'+body;const sig=root.querySelector('.sign'),foot=root.querySelector('.footer');if(sig)root.insertBefore(box,sig);else if(foot)root.insertBefore(box,foot);else root.appendChild(box);\n});`;
 if(s.includes(marker))s=s.replace(marker,inject+marker);else throw new Error('V26_INSERTION_POINT_MISSING');
 fs.writeFileSync(p,s);
}
console.log('V26_CONTENT_ENRICHED=PATCHED');