const fs=require('fs');
const p='tools/render_nidom_j1_variative_v22.js';
let s=fs.readFileSync(p,'utf8');
const replacements=[
["add(2,'salam','story','Kisah kecil: masuk kelas','Rafi masuk kelas. Teman-temannya sudah duduk. Mana tindakan terbaik: diam, berteriak, atau mengucapkan salam?',{choices:['Diam saja','Berteriak keras','Mengucapkan salam']});","add(2,'salam','support','Hadits kedua: siapa memberi salam?','يُسَلِّمُ الصَّغِيرُ عَلَى الْكَبِيرِ، وَالْمَارُّ عَلَى الْقَاعِدِ، وَالْقَلِيلُ عَلَى الْكَثِيرِ',{arab:true,sub:'Yang muda memberi salam kepada yang tua; yang berjalan kepada yang duduk; yang sedikit kepada yang banyak.',source:'HR. al-Bukhari',variant:'side'});"],
["add(6,'baik','sort','Pilih ucapan yang menenangkan','Kelompokkan: “terima kasih”, “bodoh!”, “tolong ya”, “aku tidak mau berteman!”, “maaf”, “semangat!”.');","add(6,'baik','support','Hadits kedua: kata baik adalah sedekah','الْكَلِمَةُ الطَّيِّبَةُ صَدَقَةٌ',{arab:true,sub:'Kata yang baik adalah sedekah.',source:'HR. al-Bukhari dan Muslim',variant:'card'});"],
["add(15,'jujur','story','Ilustrasi: gelas pecah','Alya tidak sengaja memecahkan gelas. Tidak ada yang melihat. Apa pilihan yang menunjukkan kejujuran?');","add(15,'jujur','support','Hadits kedua: biasakan jujur','عَلَيْكُمْ بِالصِّدْقِ',{arab:true,sub:'Hendaklah kalian selalu berlaku jujur.',source:'HR. Muslim',variant:'focus'});"],
["add(22,'kasih','story','Ilustrasi: teman sedih','Temanmu duduk sendiri karena sedih. Pilih dua tindakan yang menunjukkan kasih sayang.');","add(22,'kasih','support','Hadits kedua: sayangi yang di bumi','الرَّاحِمُونَ يَرْحَمُهُمُ الرَّحْمَنُ',{arab:true,sub:'Orang-orang penyayang akan disayangi Ar-Rahman.',source:'HR. at-Tirmidzi',variant:'ribbon'});"],
["add(26,'amanah','sort','Mana tanggung jawabku?','Pensil pinjaman, kunci kelas, pesan guru, uang yang ditemukan. Tentukan tindakan yang benar untuk masing-masing.');","add(26,'amanah','support','Hadits kedua: tunaikan amanah','أَدِّ الْأَمَانَةَ إِلَى مَنِ ائْتَمَنَكَ',{arab:true,sub:'Tunaikan amanah kepada orang yang mempercayaimu.',source:'HR. Abu Dawud dan at-Tirmidzi',variant:'stamp'});"],
["add(30,'hormat','story','Urutan adab','Ibu memanggil saat kamu bermain. Guru menjelaskan saat teman mengajak bicara. Apa tindakan pertama yang paling beradab?');","add(30,'hormat','support','Hadits kedua: ridha orang tua','رِضَا الرَّبِّ فِي رِضَا الْوَالِدِ',{arab:true,sub:'Ridha Allah terdapat pada ridha orang tua.',source:'HR. at-Tirmidzi',variant:'arch'});"],
["add(34,'tolong','game','Permainan pilih bantuan','Teman jatuh, teman ingin menyontek, adik kesulitan, teman lupa membawa alat. Pilih mana yang perlu dibantu dan bagaimana caranya.');","add(34,'tolong','support','Hadits kedua: membantu kebutuhan saudara','مَنْ كَانَ فِي حَاجَةِ أَخِيهِ كَانَ اللَّهُ فِي حَاجَتِهِ',{arab:true,sub:'Siapa membantu kebutuhan saudaranya, Allah akan membantu kebutuhannya.',source:'HR. al-Bukhari dan Muslim',variant:'steps'});"],
["add(10,'marah','support','Hadits penguat','لَا تَغْضَبْ',{arab:true,sub:'“Jangan marah.” — HR. al-Bukhari. Sebutkan satu hal yang biasanya membuatmu marah.'});","add(10,'marah','support','Hadits kedua: pesan singkat','لَا تَغْضَبْ',{arab:true,sub:'Jangan marah. Sebutkan satu hal yang biasanya membuatmu marah.',source:'HR. al-Bukhari',variant:'minimal'});"],
];
for(const [a,b] of replacements){if(!s.includes(a))throw new Error('V23_TARGET_NOT_FOUND: '+a.slice(0,35));s=s.replace(a,b)}
// Different visual grammar for every supporting-hadith page.
s=s.replace(".had .arab{font-family:Uthman,serif;",`.had.v-side{display:grid;grid-template-columns:1.35fr .65fr;gap:4mm;text-align:right;border:0;border-right:1.2mm solid #405d49;background:#f7f7f2;border-radius:3mm;padding:5mm}.had.v-card{border:0;background:#405d49;color:#fff;border-radius:4mm;padding:7mm}.had.v-card .arab,.had.v-card .tr,.had.v-card .src{color:#fff}.had.v-focus{border:0;padding:9mm 3mm}.had.v-focus .arab{font-size:31pt}.had.v-ribbon{border:0;border-radius:0 9mm 0 9mm;background:#f1eee2;padding:6mm}.had.v-stamp{border:1mm double #b8a66e;border-radius:3mm;padding:6mm}.had.v-arch{border:0;border-top:2mm solid #405d49;border-radius:18mm 18mm 3mm 3mm;background:#f7f7f2;padding:8mm 5mm}.had.v-steps{border:0;background:linear-gradient(135deg,#f7f7f2 0 72%,#e8e1c9 72%);padding:7mm 5mm;border-radius:3mm}.had.v-minimal{border:0;padding:10mm 2mm}.had.v-minimal .arab{font-size:34pt}.had .arab{font-family:Uthman,serif;`);
s=s.replace("<section class='had'><div class='arab'>${p.arab?p.body:t.had}</div><div class='tr'>${esc(p.arab?p.sub:t.tr)}</div><div class='src'>${esc(p.arab?'HR. al-Bukhari':t.src)}</div></section>","<section class='had ${p.variant?'v-'+p.variant:''}'><div class='arab'>${p.arab?p.body:t.had}</div><div class='tr'>${esc(p.arab?p.sub:t.tr)}</div><div class='src'>${esc(p.arab?(p.source||'Hadits pendukung'):t.src)}</div></section>");
fs.writeFileSync(p,s);
console.log('NIDOM_V23_HADITH_VARIETY_PATCH=PASS');