const fs=require('fs');
const p='tools/render_nidom_j1_variative_v22.js';
let s=fs.readFileSync(p,'utf8');
if(!s.includes('V30_ADAPTIVE_LOWER_ZONE')){
  s=s.replace('</style>',`\n/* V30_ADAPTIVE_LOWER_ZONE */\n.page.v30-page .sign{position:absolute!important;left:23mm!important;right:23mm!important;bottom:18mm!important;margin:0!important;min-height:0!important;height:auto!important;padding:0!important}.page.v30-page .footer{position:absolute!important;left:16mm!important;right:16mm!important;bottom:7.5mm!important}.v30-fill{margin-top:3mm;border:.28mm solid #ded8c7;border-radius:2.5mm;background:#fcfbf7;padding:3mm 4mm;overflow:hidden}.v30-fill h3{margin:0 0 2mm;font-size:7.2pt;letter-spacing:.08em;color:#405d49}.v30-prompt{font-size:7.6pt;line-height:1.35;color:#4f5650;margin-bottom:2mm}.v30-lines{height:calc(100% - 12mm);min-height:8mm;background:repeating-linear-gradient(to bottom,transparent 0,transparent 5.5mm,#d9d9d3 5.65mm,#d9d9d3 5.85mm)}\n</style>`);
  const marker='const check=await pg.evaluate';
  const inject=`await pg.evaluate(()=>{\n    const root=document.querySelector('.page');if(!root||root.querySelector('.v30-fill'))return;root.classList.add('v30-page');\n    const sig=root.querySelector('.sign');const foot=root.querySelector('.footer');if(!sig||!foot)return;\n    const pageNo=parseInt((document.querySelector('.num')?.textContent||'0'),10)||0;\n    const title=(document.querySelector('.ti')?.textContent||'').trim();\n    const box=document.createElement('section');box.className='v30-fill';\n    let prompt='Tuliskan atau ceritakan satu contoh akhlak yang kamu praktikkan hari ini.';\n    if(pageNo<=8)prompt='Apa satu kebiasaan baik yang kamu ingat dari pelajaran hari ini?';\n    else if(pageNo<=18)prompt='Apa yang akan kamu lakukan jika mengalami situasi seperti pada pelajaran hari ini?';\n    else if(pageNo<=28)prompt='Sebutkan satu contoh nyata yang bisa kamu lakukan di rumah atau di kelas.';\n    else if(pageNo<=35)prompt='Tuliskan satu tindakan yang akan kamu biasakan setelah pelajaran ini.';\n    else prompt='Catatan singkat guru/orang tua tentang praktik akhlak hari ini.';\n    box.innerHTML='<h3>MUROJAAH & CATATAN PRAKTIK</h3><div class="v30-prompt">'+prompt+'</div><div class="v30-lines"></div>';\n    root.insertBefore(box,sig);\n    const rr=root.getBoundingClientRect();const br=box.getBoundingClientRect();const sr=sig.getBoundingClientRect();\n    const targetBottom=sr.top-10;const available=Math.max(0,targetBottom-br.top);\n    if(available<28){box.remove();return;}\n    box.style.height=Math.min(available,145)+'px';\n  });`;
  if(s.includes(marker))s=s.replace(marker,inject+marker);else throw new Error('V30_INSERTION_POINT_MISSING');
  fs.writeFileSync(p,s);
}
console.log('V30_ADAPTIVE_LOWER_ZONE=PATCHED');