const fs=require('fs');
const p='tools/render_nidom_j1_variative_v22.js';
let s=fs.readFileSync(p,'utf8');
if(!s.includes('V30_KAMUS_HADITH')){
 s=s.replace('</style>',`\n/* V30_KAMUS_HADITH */\n.v27-kamus{margin-top:3mm;padding:2.8mm 3.5mm;border-top:.35mm solid #c9c2a8;border-bottom:.35mm solid #c9c2a8;background:#faf8f1}.v27-kamus h3{margin:0 0 2mm;font-size:7.4pt;letter-spacing:.08em;color:#405d49}.v27-grid{display:grid;gap:2mm}.v27-word{text-align:center;padding:1.8mm 1.2mm;border:.22mm solid #ded8c7;border-radius:2mm;background:#fff;min-height:15mm}.v27-ar{font-family:Uthman,serif!important;font-size:15pt;line-height:1.3;direction:rtl;unicode-bidi:isolate;margin-bottom:1mm;font-feature-settings:'liga' 1,'mark' 1,'mkmk' 1}.v27-id{font-size:6.8pt;line-height:1.25;color:#4f5650}.v27-src{margin-top:1.4mm;font-size:6pt;color:#7a7e77;text-align:right}.v27-kamus.compact{padding:.8mm 2mm;margin-top:.8mm}.v27-kamus.compact h3{margin:0 0 .4mm;font-size:6pt}.v27-kamus.compact .v27-word{min-height:6.5mm;padding:.3mm .8mm}.v27-kamus.compact .v27-ar{font-size:11pt;line-height:1;margin:0}.v27-kamus.compact .v27-id{font-size:5.7pt;line-height:1}.v27-kamus.compact .v27-src{display:none}.page.v30-tight-sign .sign{position:static!important;margin-top:2mm!important;min-height:12mm!important;height:auto!important;padding:0!important}.page.v30-tight-sign .footer{position:absolute!important;left:16mm!important;right:16mm!important;bottom:7.5mm!important}.page.v30-dense{padding-top:10mm!important;padding-bottom:12mm!important}.page.v30-dense .top{height:13mm!important}.page.v30-dense .title{margin-top:2mm!important}.page.v30-dense .ti{font-size:16pt!important}.page.v30-dense .badge{margin-top:1mm!important;padding:1.3mm 3mm!important}.page.v30-dense .box{margin-top:1.4mm!important;padding:1.7mm 2.6mm!important;line-height:1.12!important}.page.v30-dense .box h3{margin-bottom:1mm!important}.page.v30-dense .questions{gap:1mm!important;margin-top:1.3mm!important}.page.v30-dense .q{padding:1.1mm 2mm!important}.page.v30-dense .write{margin-top:.5mm!important;height:0!important}.page.v30-dense .sign .space{height:2mm!important}.page.v30-dense .line{margin-bottom:.5mm!important}\n</style>`);
 const marker='const check=await pg.evaluate';
 const inject=`await pg.evaluate(()=>{\n const root=document.querySelector('.page');if(!root||root.querySelector('.v27-kamus'))return;root.classList.add('v30-tight-sign');const pageNo=parseInt((document.querySelector('.num')?.textContent||'0'),10)||0;const dense=pageNo>=36;if(dense)root.classList.add('v30-dense');\n const dict={salam:[['أَفْشُوا','sebarkanlah'],['السَّلَامَ','salam'],['بَيْنَكُمْ','di antara kalian']],baik:[['فَلْيَقُلْ','hendaklah berkata'],['خَيْرًا','yang baik'],['أَوْ','atau'],['لِيَصْمُتْ','hendaklah diam']],marah:[['لَيْسَ','bukan'],['الشَّدِيدُ','orang kuat'],['يَمْلِكُ','mengendalikan'],['نَفْسَهُ','dirinya'],['عِنْدَ','ketika'],['الْغَضَبِ','marah']],jujur:[['إِنَّ','sesungguhnya'],['الصِّدْقَ','kejujuran'],['يَهْدِي','menuntun'],['إِلَى','kepada'],['الْبِرِّ','kebaikan']],kasih:[['مَنْ','siapa'],['لَا','tidak'],['يَرْحَمِ','menyayangi'],['النَّاسَ','manusia'],['يَرْحَمْهُ','menyayanginya'],['اللهُ','Allah']],amanah:[['وَإِذَا','dan apabila'],['اؤْتُمِنَ','diberi amanah'],['خَانَ','berkhianat']],hormat:[['لَيْسَ','bukan'],['مِنَّا','dari kami'],['يَرْحَمْ','menyayangi'],['صَغِيرَنَا','yang muda'],['يُوَقِّرْ','menghormati'],['كَبِيرَنَا','yang tua']],tolong:[['وَاللهُ','dan Allah'],['فِي','dalam'],['عَوْنِ','pertolongan'],['الْعَبْدِ','hamba'],['أَخِيهِ','saudaranya']]};\n const ranges=[[1,4,'salam'],[5,8,'baik'],[9,13,'marah'],[14,20,'jujur'],[21,24,'kasih'],[25,28,'amanah'],[29,32,'hormat'],[33,40,'tolong']];let theme=(ranges.find(r=>pageNo>=r[0]&&pageNo<=r[1])||[])[2]||'salam';let words=dict[theme];const count=dense?2:Math.min(4,words.length);const offset=Math.max(0,pageNo-1)%words.length;words=[...words.slice(offset),...words.slice(0,offset)].slice(0,count);const box=document.createElement('section');box.className='v27-kamus'+(dense?' compact':'');box.innerHTML='<h3>KAMUS HADITS · ARTI PER KATA</h3><div class="v27-grid" style="grid-template-columns:repeat('+count+',1fr)">'+words.map(w=>'<div class="v27-word"><div class="v27-ar">'+w[0]+'</div><div class="v27-id">'+w[1]+'</div></div>').join('')+'</div><div class="v27-src">Baca bersama guru · makna disederhanakan sesuai tingkat Jilid 1</div>';const sig=root.querySelector('.sign'),foot=root.querySelector('.footer');if(sig)root.insertBefore(box,sig);else if(foot)root.insertBefore(box,foot);else root.appendChild(box);\n});`;
 if(s.includes(marker))s=s.replace(marker,inject+marker);else throw new Error('V30_INSERTION_POINT_MISSING');fs.writeFileSync(p,s);
}
console.log('V30_KAMUS_HADITH=PATCHED');