#!/usr/bin/env python3
"""QURBATA header/footer prototype v8 — line-art Islamic footer edge, no color block, review only."""
from pathlib import Path
import asyncio,sys
from playwright.async_api import async_playwright
ROOT=Path(__file__).resolve().parents[1]
if str(ROOT/'tools') not in sys.path:sys.path.insert(0,str(ROOT/'tools'))
import render_qurbata_jilid2_p001_v19_kfgqpc as kfgloader
OUT=ROOT/'dist/qurbata-brand-prototypes/header-footer-v8';LOGO=ROOT/'books/shared/assets/qurbata-logo.svg';FONT_FAMILY='QURBATA KFGQPC Uthman Taha'
def html_doc(font_uri):
 return f'''<!doctype html><html><head><meta charset="utf-8"><style>
@page{{size:A5;margin:0}}*{{box-sizing:border-box}}@font-face{{font-family:"{FONT_FAMILY}";src:url("{font_uri}") format("truetype");font-display:block}}html,body{{margin:0;background:#fff;font-family:Arial,sans-serif}}.page{{width:148mm;height:210mm;padding:7mm 10mm 0;display:flex;flex-direction:column;overflow:hidden}}.header{{height:18mm;flex:0 0 18mm;display:grid;grid-template-columns:34mm 1fr 13mm;align-items:center}}.logo{{width:32mm;height:17.5mm;object-fit:contain}}.book-id{{text-align:center;color:#064d37;font-family:Georgia,"Times New Roman",serif;font-size:6.2pt;font-weight:700;letter-spacing:.16em}}.page-no{{justify-self:end;width:12mm;background:#064d37;color:#fff;border-bottom:1mm solid #b98a2f;border-radius:0 0 3mm 3mm;text-align:center;font-size:12pt;font-weight:700;padding:2.2mm 1mm 3mm}}.spacer{{flex:1;display:flex;align-items:center;justify-content:center;color:#ddd;font-size:8pt}}.edge-ornament{{height:12mm;flex:0 0 12mm;margin-left:-10mm;margin-right:-10mm;position:relative;overflow:hidden;background:#fff}}.edge-ornament:before{{content:'';position:absolute;left:0;right:0;bottom:0;height:6mm;background:repeating-radial-gradient(circle at 6mm 6mm,transparent 0 3.8mm,rgba(6,77,55,.22) 3.8mm 4mm,transparent 4mm 8mm);opacity:.85}}.edge-ornament:after{{content:'';position:absolute;left:0;right:0;bottom:1.2mm;height:3.8mm;background:repeating-linear-gradient(120deg,transparent 0 8mm,rgba(185,138,47,.28) 8mm 8.25mm,transparent 8.25mm 16mm),repeating-linear-gradient(60deg,transparent 0 8mm,rgba(6,77,55,.18) 8mm 8.25mm,transparent 8.25mm 16mm);opacity:.8}}.slogan{{position:absolute;top:1.1mm;z-index:3;font-family:"{FONT_FAMILY}",serif;font-size:10.3pt;line-height:1;color:#173a2d;direction:rtl;font-feature-settings:'mark' 1,'mkmk' 1;background:#fff;padding:0 2mm}}.slogan.left{{left:6mm}}.slogan.right{{right:6mm}}.center-motif{{position:absolute;left:50%;bottom:1.3mm;transform:translateX(-50%);width:14mm;height:6mm;z-index:3}}.center-motif:before{{content:'۞';position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);font-family:"{FONT_FAMILY}",serif;font-size:17pt;line-height:1;color:#b98a2f;background:#fff;padding:0 .8mm}}.center-motif:after{{content:'';position:absolute;left:0;right:0;top:50%;height:.25mm;background:linear-gradient(90deg,transparent,#064d37 18%,#b98a2f 50%,#064d37 82%,transparent);z-index:-1}}@media print{{.slogan{{color:#222}}.center-motif:before{{color:#555}}.center-motif:after{{background:linear-gradient(90deg,transparent,#777 18%,#444 50%,#777 82%,transparent)}}.edge-ornament:before{{background:repeating-radial-gradient(circle at 6mm 6mm,transparent 0 3.8mm,rgba(0,0,0,.18) 3.8mm 4mm,transparent 4mm 8mm)}}.edge-ornament:after{{background:repeating-linear-gradient(120deg,transparent 0 8mm,rgba(0,0,0,.16) 8mm 8.25mm,transparent 8.25mm 16mm),repeating-linear-gradient(60deg,transparent 0 8mm,rgba(0,0,0,.1) 8mm 8.25mm,transparent 8.25mm 16mm)}}}}
</style></head><body><main class="page"><header class="header"><img class="logo" src="{LOGO.resolve().as_uri()}"><div class="book-id">QURBATA · JILID 1</div><div class="page-no">01</div></header><div class="spacer">AREA MATERI UTAMA — prototype identitas saja</div><footer class="edge-ornament"><span class="slogan left">قُرْآنٌ · لُغَةٌ · أَدَبٌ</span><span class="center-motif"></span><span class="slogan right">تَعَلَّمْ · اِعْمَلْ · عَلِّمْ</span></footer></main></body></html>'''
def free_path(base):
 if not base.exists():return base
 for n in range(1,100):
  p=base.with_name(base.stem+f'-R{n}'+base.suffix)
  if not p.exists():return p
 raise RuntimeError('NO_FREE_OUTPUT_FILENAME')
async def render():
 OUT.mkdir(parents=True,exist_ok=True);font,src=kfgloader.discover_font(None,None,OUT);h=OUT/'QURBATA-HEADER-FOOTER-PROTOTYPE-V8-LINE-ART.html';h.write_text(html_doc(font.resolve().as_uri()),encoding='utf-8');pdf=free_path(OUT/'QURBATA-HEADER-FOOTER-PROTOTYPE-V8-LINE-ART.pdf');png=free_path(OUT/'QURBATA-HEADER-FOOTER-PROTOTYPE-V8-LINE-ART.png')
 async with async_playwright() as pw:
  b=await pw.chromium.launch();p=await b.new_page(viewport={'width':1120,'height':1584},device_scale_factor=2);await p.goto(h.resolve().as_uri(),wait_until='networkidle');await p.evaluate('document.fonts.ready')
  if not await p.evaluate(f"()=>document.fonts.check('10.3pt \\\"{FONT_FAMILY}\\\"','قُرْآنٌ تَعَلَّمْ')"):raise RuntimeError('QURBATA_FOOTER_KFGQPC_BINDING_FAIL')
  await p.screenshot(path=str(png),full_page=True);await p.pdf(path=str(pdf),format='A5',print_background=True,margin={'top':'0','right':'0','bottom':'0','left':'0'});await b.close()
 print('QURBATA_HEADER_FOOTER_PROTOTYPE_V8=PASS');print('PRODUCTION_PAGES_MODIFIED=NO');print('FOOTER_COLOR_BLOCK=REMOVED');print('FOOTER_SQUARE_ORNAMENT=REMOVED');print('FOOTER_STYLE=ISLAMIC_LINE_ART_EDGE');print('FOOTER_ARABIC_FONT=KFGQPC_UTHMAN_TAHA');print(f'FONT_SOURCE={src}');print(f'PDF={pdf.relative_to(ROOT)}')
if __name__=='__main__':asyncio.run(render())
