#!/usr/bin/env python3
"""QURBATA header/footer prototype v3 — continuous ornamental divider blocks, review only."""
from pathlib import Path
import asyncio,sys
from playwright.async_api import async_playwright
ROOT=Path(__file__).resolve().parents[1]
if str(ROOT/'tools') not in sys.path:sys.path.insert(0,str(ROOT/'tools'))
import render_qurbata_jilid2_p001_v19_kfgqpc as kfgloader
OUT=ROOT/'dist/qurbata-brand-prototypes/header-footer-v3';LOGO=ROOT/'books/shared/assets/qurbata-logo.svg';FONT_FAMILY='QURBATA KFGQPC Uthman Taha'
def html_doc(font_uri):
 return f'''<!doctype html><html><head><meta charset="utf-8"><style>
@page{{size:A5;margin:0}}*{{box-sizing:border-box}}@font-face{{font-family:"{FONT_FAMILY}";src:url("{font_uri}") format("truetype");font-display:block}}html,body{{margin:0;background:#fff;font-family:Arial,sans-serif}}.page{{width:148mm;height:210mm;padding:7mm 10mm;display:flex;flex-direction:column;justify-content:space-between}}.header-wrap{{height:29mm}}.header-row{{height:17mm;display:grid;grid-template-columns:34mm 1fr 13mm;align-items:center}}.logo{{width:32mm;height:17.5mm;object-fit:contain}}.book-id{{text-align:center;color:#064d37;font-family:Georgia,"Times New Roman",serif;font-size:6.2pt;font-weight:700;letter-spacing:.16em}}.page-no{{justify-self:end;width:12mm;background:#064d37;color:#fff;border-bottom:1mm solid #b98a2f;border-radius:0 0 3mm 3mm;text-align:center;font-size:12pt;font-weight:700;padding:2.2mm 1mm 3mm}}.divider{{height:8mm;position:relative;margin-top:1.2mm}}.rail{{position:absolute;left:0;right:0;top:3.6mm;height:.28mm;background:#064d37}}.rail.gold{{top:4.55mm;height:.18mm;background:#b98a2f;opacity:.8}}.orn-left,.orn-right{{position:absolute;top:1.15mm;width:19mm;height:5mm}}.orn-left{{left:13mm}}.orn-right{{right:13mm;transform:scaleX(-1)}}.orn-left:before,.orn-right:before{{content:'';position:absolute;left:0;top:1.4mm;width:8mm;height:2.2mm;border-left:.35mm solid #064d37;border-top:.35mm solid #064d37;border-bottom:.35mm solid #064d37}}.orn-left:after,.orn-right:after{{content:'';position:absolute;left:6.8mm;top:.2mm;width:4.2mm;height:4.2mm;border:.3mm solid #b98a2f;transform:rotate(45deg);background:#fff}}.node{{position:absolute;left:50%;top:.35mm;transform:translateX(-50%);width:9mm;height:6.5mm;background:#fff}}.node:before,.node:after{{content:'';position:absolute;left:50%;top:50%;width:4.8mm;height:4.8mm;border:.34mm solid #064d37;transform:translate(-50%,-50%) rotate(45deg)}}.node:after{{width:3.1mm;height:3.1mm;border-color:#b98a2f;transform:translate(-50%,-50%) rotate(0deg)}}.node-dot{{position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);width:1.05mm;height:1.05mm;border-radius:50%;background:#064d37;z-index:2}}.micro{{position:absolute;top:2.9mm;width:2mm;height:2mm;border:.25mm solid #b98a2f;transform:rotate(45deg);background:#fff}}.m1{{left:38mm}}.m2{{right:38mm}}.spacer{{flex:1;display:flex;align-items:center;justify-content:center;color:#ddd;font-size:8pt}}.footer{{height:21mm}}.footer .divider{{margin-top:0;margin-bottom:1mm}}.footer .orn-left,.footer .orn-right{{width:24mm}}.footer .orn-left{{left:9mm}}.footer .orn-right{{right:9mm}}.footer .orn-left:before,.footer .orn-right:before{{width:11mm}}.footer .orn-left:after,.footer .orn-right:after{{left:9.8mm}}.footer-text{{display:flex;justify-content:space-between;align-items:center;color:#064d37;padding-top:.2mm}}.ar{{font-family:"{FONT_FAMILY}",serif;font-size:11pt;line-height:1.1;direction:rtl;font-feature-settings:'mark' 1,'mkmk' 1}}.note{{font-size:4.6pt;color:#999;text-align:center;margin-top:.8mm}}
</style></head><body><main class="page"><section class="header-wrap"><div class="header-row"><img class="logo" src="{LOGO.resolve().as_uri()}"><div class="book-id">QURBATA · JILID 1</div><div class="page-no">01</div></div><div class="divider"><span class="rail"></span><span class="rail gold"></span><span class="orn-left"></span><span class="orn-right"></span><span class="micro m1"></span><span class="micro m2"></span><span class="node"><span class="node-dot"></span></span></div></section><div class="spacer">AREA MATERI UTAMA — prototype identitas saja</div><section class="footer"><div class="divider"><span class="rail"></span><span class="rail gold"></span><span class="orn-left"></span><span class="orn-right"></span><span class="micro m1"></span><span class="micro m2"></span><span class="node"><span class="node-dot"></span></span></div><div class="footer-text"><span class="ar">قُرْآنٌ · لُغَةٌ · أَدَبٌ</span><span class="ar">تَعَلَّمْ · اِعْمَلْ · عَلِّمْ</span></div><div class="note">QURBATA Ornament Prototype v3 · continuous divider block</div></section></main></body></html>'''
def free_path(base):
 if not base.exists():return base
 for n in range(1,100):
  p=base.with_name(base.stem+f'-R{n}'+base.suffix)
  if not p.exists():return p
 raise RuntimeError('NO_FREE_OUTPUT_FILENAME')
async def render():
 OUT.mkdir(parents=True,exist_ok=True);font,src=kfgloader.discover_font(None,None,OUT);h=OUT/'QURBATA-HEADER-FOOTER-ORNAMENT-PROTOTYPE-V3.html';h.write_text(html_doc(font.resolve().as_uri()),encoding='utf-8');pdf=free_path(OUT/'QURBATA-HEADER-FOOTER-ORNAMENT-PROTOTYPE-V3.pdf');png=free_path(OUT/'QURBATA-HEADER-FOOTER-ORNAMENT-PROTOTYPE-V3.png')
 async with async_playwright() as pw:
  b=await pw.chromium.launch();p=await b.new_page(viewport={'width':1120,'height':1584},device_scale_factor=2);await p.goto(h.resolve().as_uri(),wait_until='networkidle');await p.evaluate('document.fonts.ready')
  if not await p.evaluate(f"()=>document.fonts.check('11pt \\\"{FONT_FAMILY}\\\"','قُرْآنٌ تَعَلَّمْ')"):raise RuntimeError('QURBATA_FOOTER_KFGQPC_BINDING_FAIL')
  await p.screenshot(path=str(png),full_page=True);await p.pdf(path=str(pdf),format='A5',print_background=True,margin={'top':'0','right':'0','bottom':'0','left':'0'});await b.close()
 print('QURBATA_ORNAMENT_PROTOTYPE_V3=PASS');print('PRODUCTION_PAGES_MODIFIED=NO');print('DIVIDER=CONTINUOUS_ORNAMENTAL_BLOCK');print('CENTER=LITERAL_Q_REMOVED|ABSTRACT_GEOMETRIC_NODE');print('FOOTER_ARABIC_FONT=KFGQPC_UTHMAN_TAHA');print(f'FONT_SOURCE={src}');print(f'PDF={pdf.relative_to(ROOT)}')
if __name__=='__main__':asyncio.run(render())
