const { chromium } = require('playwright');
const { PDFDocument } = require('pdf-lib');
const fs=require('fs'), path=require('path');
const OUT=path.resolve(__dirname,'../dist/nidom-akhlak/j1-variative-v22'); fs.mkdirSync(OUT,{recursive:true});
const logo='../../shared/assets/qurbata-logo.svg';
const H={
 salam:{title:'Aku Membiasakan Salam',ar:'السَّلَامُ',had:'أَفْشُوا السَّلَامَ بَيْنَكُمْ',tr:'Sebarkanlah salam di antara kalian.',src:'HR. Muslim'},
 baik:{title:'Aku Berkata Baik',ar:'الْكَلَامُ الطَّيِّبُ',had:'فَلْيَقُلْ خَيْرًا أَوْ لِيَصْمُتْ',tr:'Hendaklah berkata baik atau diam.',src:'HR. al-Bukhari dan Muslim'},
 marah:{title:'Aku Mengendalikan Marah',ar:'ضَبْطُ الْغَضَبِ',had:'لَيْسَ الشَّدِيدُ بِالصُّرَعَةِ، إِنَّمَا الشَّدِيدُ الَّذِي يَمْلِكُ نَفْسَهُ عِنْدَ الْغَضَبِ',tr:'Orang kuat adalah yang mampu mengendalikan dirinya ketika marah.',src:'HR. al-Bukhari dan Muslim'},
 jujur:{title:'Aku Berkata Jujur',ar:'الصِّدْقُ',had:'إِنَّ الصِّدْقَ يَهْدِي إِلَى الْبِرِّ',tr:'Kejujuran menuntun kepada kebaikan.',src:'HR. al-Bukhari dan Muslim'},
 kasih:{title:'Aku Menyayangi Sesama',ar:'الرَّحْمَةُ',had:'مَنْ لَا يَرْحَمِ النَّاسَ لَا يَرْحَمْهُ اللهُ',tr:'Siapa yang tidak menyayangi manusia, Allah tidak menyayanginya.',src:'HR. Muslim'},
 amanah:{title:'Aku Menjaga Amanah',ar:'الْأَمَانَةُ',had:'وَإِذَا اؤْتُمِنَ خَانَ',tr:'Apabila diberi amanah, ia berkhianat.',src:'Bagian hadits tanda munafik — HR. al-Bukhari dan Muslim'},
 hormat:{title:'Aku Menghormati Orang Tua dan Guru',ar:'الْبِرُّ وَالْأَدَبُ',had:'لَيْسَ مِنَّا مَنْ لَمْ يَرْحَمْ صَغِيرَنَا وَيُوَقِّرْ كَبِيرَنَا',tr:'Bukan golongan kami yang tidak menyayangi yang muda dan menghormati yang tua.',src:'HR. at-Tirmidzi'},
 tolong:{title:'Aku Suka Menolong dan Berbagi',ar:'التَّعَاوُنُ',had:'وَاللَّهُ فِي عَوْنِ الْعَبْدِ مَا كَانَ الْعَبْدُ فِي عَوْنِ أَخِيهِ',tr:'Allah menolong hamba selama ia menolong saudaranya.',src:'HR. Muslim'}
};
const P=[]; function add(n,theme,mode,head,body,opts={}){P.push({n,theme,mode,head,body,...opts})}
add(1,'salam','hadith','Dengar dan tirukan','Guru menalqinkan salam. Anak menirukan dan mengenali kapan salam diucapkan.');
add(2,'salam','story','Kisah kecil: masuk kelas','Rafi masuk kelas. Teman-temannya sudah duduk. Mana tindakan terbaik: diam, berteriak, atau mengucapkan salam?',{choices:['Diam saja','Berteriak keras','Mengucapkan salam']});
add(3,'salam','dialog','Lengkapi dialog','Guru: “Assalamu’alaikum.”\nAku: “....................”\nLalu praktikkan dengan teman.');
add(4,'salam','mission','Misi salam 1 hari','Berilah salam saat masuk rumah dan kelas. Minta Orang Tua/Wali dan Guru memberi tanda bila dilakukan tanpa diingatkan.');
add(5,'baik','hadith','Kata baik atau diam','Dengarkan hadits. Sebutkan dua contoh ucapan baik yang mudah kamu gunakan hari ini.');
add(6,'baik','sort','Pilih ucapan yang menenangkan','Kelompokkan: “terima kasih”, “bodoh!”, “tolong ya”, “aku tidak mau berteman!”, “maaf”, “semangat!”.');
add(7,'baik','case','Kasus: teman kalah permainan','Temanmu kalah dan sedih. Apa ucapan terbaik? Pilih lalu jelaskan satu alasan sederhana.',{choices:['Makanya jangan ikut!','Tidak apa-apa, coba lagi ya','Aku senang kamu kalah']});
add(8,'baik','mission','Ganti kata buruk','Hari ini ubah tiga ucapan yang kasar menjadi kalimat baik. Guru/Orang Tua menilai praktiknya.');
add(9,'marah','hadith','Siapa anak yang kuat?','Dengarkan hadits tentang orang kuat. Kuat bukan memukul, tetapi mampu menjaga diri saat marah.');
add(10,'marah','support','Hadits penguat','لَا تَغْضَبْ',{arab:true,sub:'“Jangan marah.” — HR. al-Bukhari. Sebutkan satu hal yang biasanya membuatmu marah.'});
add(11,'marah','story','Ilustrasi: berebut buku','Dua anak ingin buku yang sama. Satu menarik, satu mulai berteriak. Apa yang mungkin terjadi jika keduanya terus marah?');
add(12,'marah','sequence','Urutkan tindakan aman','Urutkan: bicara baik — berhenti — tenangkan diri. Lalu praktikkan urutannya.');
add(13,'marah','mission','Tantangan 2 hari','Saat mulai marah: berhenti, tenang, lalu bicara baik. Catat satu keberhasilan bersama guru/orang tua.');
add(14,'jujur','hadith','Jujur membawa kebaikan','Dengarkan hadits. Jujur berarti mengatakan keadaan yang sebenarnya walaupun kita takut dimarahi.');
add(15,'jujur','story','Ilustrasi: gelas pecah','Alya tidak sengaja memecahkan gelas. Tidak ada yang melihat. Apa pilihan yang menunjukkan kejujuran?');
add(16,'jujur','case','Tiga kasus jujur','1) PR belum selesai. 2) Menemukan penghapus. 3) Menumpahkan air. Pilih jawaban jujur untuk setiap kasus.');
add(17,'jujur','dialog','Latihan mengakui kesalahan','Lengkapi: “Bu/Pak, saya mau berkata jujur. Saya ............ Saya minta maaf dan akan ............”');
add(18,'jujur','mission','Tantangan jujur 3 hari','Berani berkata benar tanpa membuat alasan palsu. Orang tua/guru mencatat satu contoh nyata.');
add(19,null,'quiz','Checkpoint I','Campuran salam, berkata baik, mengendalikan marah, dan jujur.',{questions:['Pilih respons terbaik saat masuk kelas.','Benar/Salah: memukul menunjukkan kita kuat. Jelaskan singkat.','Pasangkan ucapan baik dengan situasinya.','Apa yang kamu katakan jika melakukan kesalahan?']});
add(20,null,'casepack','Checkpoint II — kasus terpadu','Selesaikan tiga kasus dan satu role play.',{questions:['Masuk rumah saat orang tua menerima tamu. Apa yang kamu lakukan?','Teman mengejekmu dan kamu mulai marah. Apa urutan tindakanmu?','Kamu lupa mengerjakan tugas. Jawaban jujurmu?','Role play: salam + ucapan baik kepada guru.']});
add(21,'kasih','hadith','Kasih sayang itu tindakan','Dengarkan hadits. Kasih sayang tampak dari cara kita berbicara, membantu, dan tidak menyakiti.');
add(22,'kasih','story','Ilustrasi: teman sedih','Temanmu duduk sendiri karena sedih. Pilih dua tindakan yang menunjukkan kasih sayang.');
add(23,'kasih','case','Apa yang bisa kulakukan?','Adik kesulitan membawa buku. Teman sakit. Teman baru belum punya pasangan. Pilih tindakan nyata untuk masing-masing.');
add(24,'kasih','mission','Misi rahmah','Lakukan satu bantuan nyata hari ini. Gambar/tulis singkat apa yang kamu lakukan dan siapa yang terbantu.');
add(25,'amanah','hadith','Apa itu amanah?','Amanah adalah menjaga barang, tugas, dan kepercayaan. Dengarkan hadits lalu bedakan milikku, milik teman, dan barang pinjaman.');
add(26,'amanah','sort','Mana tanggung jawabku?','Pensil pinjaman, kunci kelas, pesan guru, uang yang ditemukan. Tentukan tindakan yang benar untuk masing-masing.');
add(27,'amanah','case','Barang pinjaman rusak','Kamu meminjam penggaris lalu patah. Apa yang harus dilakukan? Pilih: sembunyikan, kembalikan diam-diam, atau jujur dan bertanggung jawab.');
add(28,'amanah','practice','Praktik amanah','Guru memberikan satu barang untuk dipinjam. Terima dengan baik, jaga, gunakan seperlunya, lalu kembalikan. Guru memberi cek praktik.');
add(29,'hormat','hadith','Hormat itu terlihat','Dengarkan hadits. Hari ini fokus pada suara lembut, mendengar saat dinasihati, dan tidak memotong pembicaraan.');
add(30,'hormat','story','Urutan adab','Ibu memanggil saat kamu bermain. Guru menjelaskan saat teman mengajak bicara. Apa tindakan pertama yang paling beradab?');
add(31,'hormat','practice','Role play adab','Praktikkan: menjawab panggilan orang tua, meminta izin kepada guru, dan menerima nasihat tanpa membantah kasar.');
add(32,'hormat','mission','Misi rumah–sekolah','Lakukan satu bantuan untuk orang tua dan satu bentuk adab kepada guru. Minta keduanya memberi tanda.');
add(33,'tolong','hadith','Menolong dalam kebaikan','Dengarkan hadits. Menolong tidak berarti ikut melakukan kesalahan. Bedakan bantuan baik dan bantuan yang tidak boleh.');
add(34,'tolong','game','Permainan pilih bantuan','Teman jatuh, teman ingin menyontek, adik kesulitan, teman lupa membawa alat. Pilih mana yang perlu dibantu dan bagaimana caranya.');
add(35,'tolong','mission','Aksi nyata berbagi','Tolong atau berbagi satu hal hari ini. Tuliskan/gambar apa yang terjadi dan bagaimana perasaan orang yang dibantu.');
add(36,null,'quiz','Quiz Akhir — kenali perilaku','Kenali 8 kompetensi dari situasi sederhana.',{questions:['Salam','Berkata baik','Menahan marah','Jujur','Kasih sayang','Amanah','Hormat','Menolong/berbagi']});
add(37,null,'casepack','Penalaran Akhir','Pilih tindakan dan beri alasan sederhana.',{questions:['Teman mengejek lalu kamu marah.','Menemukan uang di kelas.','Ibu memanggil ketika kamu bermain.','Teman meminta jawaban ulangan.']});
add(38,null,'stations','Stasiun Praktik','Guru menilai praktik nyata.',{questions:['Salam kepada guru','Ucapan baik kepada teman','Respons saat marah','Mengakui kesalahan','Mengembalikan barang pinjaman','Menjawab panggilan orang tua/guru']});
add(39,null,'reflection','Jejak Kebiasaanku','Anak, orang tua, dan guru menilai kebiasaan tanpa hukuman.',{questions:['Aku sudah sering melakukan','Aku kadang masih lupa','Aku ingin memperbaiki satu kebiasaan ini']});
add(40,null,'report','Rapor NIDOM Jilid 1','Profil 8 kompetensi: Mulai Tumbuh / Berkembang / Membudaya. Tambahkan kekuatan anak dan satu target Jilid 2.');

function esc(s=''){return String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}
const css=`@font-face{font-family:Uthman;src:url('../../../.build-fonts/UthmanTaha.woff2') format('woff2');font-display:block}@page{size:176mm 250mm;margin:0}*{box-sizing:border-box}html,body{margin:0;background:#eee;font-family:Arial,sans-serif}.page{width:176mm;height:250mm;background:#fff;padding:13mm 16mm 14mm;position:relative;overflow:hidden;color:#243129}.top{height:15mm;border-bottom:.35mm solid #b8a66e;display:grid;grid-template-columns:11mm 1fr 12mm;gap:4mm}.logo{width:10mm;height:11mm;object-fit:contain}.k{font-size:7pt;font-weight:700;letter-spacing:.08em;color:#5f705d;padding-top:1mm}.num{height:12mm;background:#405d49;color:#fff;display:flex;align-items:center;justify-content:center;font-weight:800;border-radius:0 0 2.5mm 2.5mm;border-bottom:1mm solid #b8a66e}.title{margin-top:5mm;display:grid;grid-template-columns:1fr auto;gap:5mm;align-items:end}.ti{font-size:18pt;font-weight:800}.ar{font-family:Uthman,serif;direction:rtl;unicode-bidi:isolate;font-size:25pt;color:#5f705d;font-feature-settings:'liga' 1,'mark' 1,'mkmk' 1}.badge{margin-top:3mm;background:#f2f4ef;border-radius:3mm;padding:2.8mm 4mm;font-size:8pt;font-weight:700}.had{margin-top:4mm;border-top:.35mm solid #d8d2bd;border-bottom:.35mm solid #d8d2bd;padding:3.5mm 2mm;text-align:center}.had .arab{font-family:Uthman,serif;direction:rtl;unicode-bidi:isolate;font-size:23pt;line-height:1.45;font-feature-settings:'liga' 1,'mark' 1,'mkmk' 1}.tr{font-size:8.3pt;margin-top:1mm}.src{font-size:6.7pt;color:#777;margin-top:1mm}.box{margin-top:4mm;background:#f7f7f2;border-radius:3mm;padding:4mm;font-size:8.5pt;line-height:1.45}.box h3{font-size:8pt;letter-spacing:.08em;color:#405d49;margin:0 0 2.5mm}.choices,.questions{display:grid;gap:2.5mm;margin-top:3mm}.choice,.q{border:.3mm solid #d7d7cf;border-radius:2mm;padding:2.6mm 3mm}.sq{display:inline-block;width:3.5mm;height:3.5mm;border:.35mm solid #617a67;margin-right:2mm;vertical-align:middle}.twocol{display:grid;grid-template-columns:1fr 1fr;gap:4mm;margin-top:4mm}.write{height:18mm;margin-top:3mm;background:repeating-linear-gradient(to bottom,transparent 0,transparent 5mm,#d9d9d3 5.1mm,#d9d9d3 5.3mm)}.mission{border:.45mm solid #b8a66e;background:#fbfaf5}.sign{position:absolute;left:23mm;right:23mm;bottom:18mm;display:grid;grid-template-columns:1fr 1fr;gap:15mm;text-align:center;font-size:6.7pt;color:#59645c}.space{height:7mm}.line{border-top:.25mm solid #8f978f;margin:0 auto 1mm;width:38mm}.footer{position:absolute;left:16mm;right:16mm;bottom:7.5mm;border-top:.25mm solid #d0c49a;padding-top:2.5mm;display:flex;justify-content:space-between;font-size:6.5pt;color:#777}.rubric{display:grid;grid-template-columns:1.8fr repeat(3,1fr);gap:1px;background:#ccc;margin-top:4mm}.rubric div{background:#fff;padding:2.5mm;font-size:7.5pt}`;
const label={hadith:'HADITS INTI',support:'HADITS PENDUKUNG',story:'KISAH / ILUSTRASI',dialog:'DIALOG / ROLE PLAY',mission:'TANTANGAN KEBIASAAN',sort:'PILAH & COCOKKAN',case:'PENALARAN KASUS',sequence:'URUTKAN TINDAKAN',practice:'PRAKTIK LANGSUNG',game:'PERMAINAN PILIH SIKAP',quiz:'QUIZ KUMULATIF',casepack:'KASUS TERPADU',stations:'STASIUN PRAKTIK',reflection:'REFLEKSI',report:'RAPOR'};
function sig(){return `<section class='sign'><div><div class='space'></div><div class='line'></div>Orang Tua / Wali</div><div><div class='space'></div><div class='line'></div>Guru</div></section>`}
function renderPage(p){const t=p.theme?H[p.theme]:null; let main='';
 if(t && ['hadith','support'].includes(p.mode)){main=`<section class='had'><div class='arab'>${p.arab?p.body:t.had}</div><div class='tr'>${esc(p.arab?p.sub:t.tr)}</div><div class='src'>${esc(p.arab?'HR. al-Bukhari':t.src)}</div></section><section class='box'><h3>${esc(p.head)}</h3>${esc(p.arab?'':p.body)}</section>`}
 else if(p.mode==='story'){main=`<section class='box'><h3>${esc(p.head)}</h3><p>${esc(p.body)}</p><div class='choices'>${(p.choices||['Apa yang terjadi?','Apa tindakan terbaik?','Mengapa?']).map(x=>`<div class='choice'><span class='sq'></span>${esc(x)}</div>`).join('')}</div></section><section class='box'><h3>AKU BERPIKIR</h3>Ceritakan jawabanmu dengan satu kalimat sederhana.<div class='write'></div></section>`}
 else if(['dialog','case','sequence','sort','game'].includes(p.mode)){main=`<section class='box'><h3>${esc(p.head)}</h3><p>${esc(p.body).replace(/\n/g,'<br>')}</p>${p.choices?`<div class='choices'>${p.choices.map(x=>`<div class='choice'><span class='sq'></span>${esc(x)}</div>`).join('')}</div>`:''}<div class='write'></div></section><section class='box'><h3>MUROJAAH SPIRAL</h3>Sebutkan satu kebiasaan baik dari tema sebelumnya yang masih kamu ingat.</section>`}
 else if(['mission','practice'].includes(p.mode)){main=`<section class='box mission'><h3>${esc(p.head)}</h3><p>${esc(p.body)}</p><div class='choices'><div class='choice'><span class='sq'></span>Sudah mencoba</div><div class='choice'><span class='sq'></span>Masih perlu dibantu</div><div class='choice'><span class='sq'></span>Bisa dilakukan tanpa diingatkan</div></div></section><section class='box'><h3>CATATAN PENDAMPING</h3><div class='write'></div></section>`}
 else if(['quiz','casepack','stations','reflection'].includes(p.mode)){main=`<section class='box'><h3>${esc(p.head)}</h3><p>${esc(p.body)}</p><div class='questions'>${(p.questions||[]).map((x,i)=>`<div class='q'><b>${i+1}.</b> ${esc(x)}<div class='write' style='height:${p.mode==='quiz'?'7':'10'}mm'></div></div>`).join('')}</div></section>`}
 else if(p.mode==='report'){main=`<section class='box'><h3>PROFIL KOMPETENSI</h3><div class='rubric'><div>Kompetensi</div><div>Mulai Tumbuh</div><div>Berkembang</div><div>Membudaya</div>${['Salam','Berkata baik','Menahan marah','Jujur','Kasih sayang','Amanah','Hormat','Menolong & berbagi'].map(x=>`<div>${x}</div><div>□</div><div>□</div><div>□</div>`).join('')}</div></section><section class='twocol'><div class='box'><h3>KEKUATAN ANAK</h3><div class='write'></div></div><div class='box'><h3>TARGET JILID 2</h3><div class='write'></div></div></section>`}
 const title=t?t.title:p.head, ar=t?`<div class='ar'>${t.ar}</div>`:''; return `<!doctype html><html><head><meta charset='utf-8'><style>${css}</style></head><body><main class='page'><header class='top'><img class='logo' src='${logo}'><div class='k'>QURBATA NIDOM · JILID 1 · VARIATIVE v2.2</div><div class='num'>${String(p.n).padStart(2,'0')}</div></header><section class='title'><div class='ti'>${esc(title)}</div>${ar}</section><section class='badge'>${label[p.mode]||'LATIHAN'} · ${esc(p.head)}</section>${main}${sig()}<footer class='footer'><span>QURBATA NIDOM · BEGINNER ZERO · VARIATIVE REPETITION</span><span>${String(p.n).padStart(2,'0')}</span></footer></main></body></html>`}
(async()=>{const b=await chromium.launch({headless:true}); const master=await PDFDocument.create(); const modes=[]; for(const p of P){const html=path.join(OUT,`page-${String(p.n).padStart(3,'0')}.html`);fs.writeFileSync(html,renderPage(p));const pg=await b.newPage({viewport:{width:1331,height:1890},deviceScaleFactor:2});await pg.goto('file://'+html,{waitUntil:'networkidle'});await pg.evaluate(()=>document.fonts.ready);const check=await pg.evaluate(()=>({font:document.fonts.check('30px Uthman','السَّلَامُ'),overflow:document.querySelector('.page').scrollHeight>document.querySelector('.page').clientHeight+2,logo:document.querySelector('.logo').naturalWidth>0}));if(!check.font)throw new Error(`UTHMAN_FAIL_P${p.n}`);if(check.overflow)throw new Error(`OVERFLOW_P${p.n}`);if(!check.logo)throw new Error(`LOGO_FAIL_P${p.n}`);const pdf=path.join(OUT,`QURBATA-NIDOM-J1-P${String(p.n).padStart(3,'0')}-v2.2.pdf`);await pg.pdf({path:pdf,width:'176mm',height:'250mm',printBackground:true,margin:{top:'0',right:'0',bottom:'0',left:'0'}});const bytes=fs.readFileSync(pdf),doc=await PDFDocument.load(bytes);const [cp]=await master.copyPages(doc,[0]);master.addPage(cp);modes.push(p.mode);await pg.close()}fs.writeFileSync(path.join(OUT,'QURBATA-NIDOM-J1-P001-P040-PRINT-MASTER-v2.2.pdf'),await master.save());const distinctWindows=[];for(let i=0;i<=modes.length-5;i++)distinctWindows.push(new Set(modes.slice(i,i+5)).size);if(Math.min(...distinctWindows)<3)throw new Error('VARIETY_GATE_FAIL');fs.writeFileSync(path.join(OUT,'MANIFEST-v2.2.json'),JSON.stringify({version:'2.2',pageCount:P.length,competencies:8,minDistinctModesPer5Pages:Math.min(...distinctWindows),font:'KFGQPC Uthman Taha Naskh',logo:true},null,2));await b.close();console.log('J1_VARIATIVE_V22=PASS');})();