const fs=require('fs');
const path=require('path');
const base=path.resolve(__dirname,'render_nidom_j5_v01.js');
if(!fs.existsSync(base)) throw new Error('J5_BASE_RENDERER_MISSING');
let src=fs.readFileSync(base,'utf8');
const cut=src.indexOf('(async()=>{');
if(cut<0) throw new Error('J5_ASYNC_ANCHOR_MISSING');
src=src.slice(0,cut);
src=src.replace('font-display:swap','font-display:block');
const tail=`(async()=>{const fp=path.resolve(__dirname,'../.build-fonts/UthmanTaha.woff2');if(!fs.existsSync(fp))throw Error('FONT_MISSING');const font=fs.readFileSync(fp).toString('base64'),b=await chromium.launch({headless:true}),master=await PDFDocument.create();for(const p of P){console.log('P'+String(p.n).padStart(3,'0')+'_START');const pg=await b.newPage();await pg.setContent(html(p,font));await pg.evaluate(()=>document.fonts.ready);const hasArabic=!!(p.t&&p.hi!==null&&p.hi!==undefined&&H[p.t]&&H[p.t][p.hi]);const g=await pg.evaluate(hasArabic=>({font:hasArabic?document.fonts.check('30px Uthman','الْخَيْرُ'):true,scroll:document.querySelector('.p').scrollHeight,client:document.querySelector('.p').clientHeight}),hasArabic);if(!g.font||g.scroll>g.client+2)throw Error('GATE_P'+p.n+' '+JSON.stringify(g));let buf=await pg.pdf({width:'176mm',height:'250mm',printBackground:true});const stampDoc=await PDFDocument.load(buf),stampImg=await stampDoc.embedPng(logo),stampPage=stampDoc.getPage(0),stampH=stampPage.getHeight();stampPage.drawImage(stampImg,{x:45,y:stampH-70,width:40,height:40});buf=Buffer.from(await stampDoc.save());fs.writeFileSync(path.join(OUT,'QURBATA-NIDOM-J5-P'+String(p.n).padStart(3,'0')+'-v0.2.pdf'),buf);const d=await PDFDocument.load(buf);(await master.copyPages(d,d.getPageIndices())).forEach(x=>master.addPage(x));await pg.close();console.log('P'+String(p.n).padStart(3,'0')+'=PASS')}fs.writeFileSync(path.join(OUT,'QURBATA-NIDOM-J5-P001-P040-PRINT-MASTER-v0.2.pdf'),await master.save());await b.close();console.log('PAGE_COUNT=40');console.log('FONT_UTHMAN=PASS');console.log('OFFICIAL_LOGO=PDF_DIRECT_STAMP');console.log('REASONING_DENSITY=ADAPTIVE_DALIL2_OPEN5');console.log('OVERFLOW=0')})().catch(e=>{console.error(e);process.exit(1)});`;
console.log('J5_EXECUTION_ENGINE=KNOWN_GOOD_J4_PATTERN');
eval(src+tail);
