const fs=require('fs');const path=require('path');
const basePath=path.resolve(__dirname,'render_nidom_j4_v01.js');
const logoPath=path.resolve(__dirname,'../assets/qurbata/QURBATA-LOGO-v1.0-FROZEN-header.png');
if(!fs.existsSync(basePath)) throw new Error('J4_BASE_RENDERER_MISSING');
if(!fs.existsSync(logoPath)) throw new Error('QURBATA_FROZEN_LOGO_MISSING');
const logo=fs.readFileSync(logoPath).toString('base64');
let src=fs.readFileSync(basePath,'utf8');
const oldLogoCss='.logo{width:10mm;height:10mm;border:1mm solid #55705d;border-radius:50%;display:flex;align-items:center;justify-content:center;font-weight:900;font-size:9pt}';
const newLogoCss='.logo{width:14mm;height:14mm;object-fit:contain;display:block;flex:0 0 auto}';
if(!src.includes(oldLogoCss)) throw new Error('J4_LOGO_CSS_ANCHOR_MISSING');
src=src.replace(oldLogoCss,newLogoCss);
const oldLogoHtml='<div class=logo>Q</div>';
const newLogoHtml=`<img class=logo alt="QURBATA" src="data:image/png;base64,${logo}">`;
if(!src.includes(oldLogoHtml)) throw new Error('J4_LOGO_HTML_ANCHOR_MISSING');
src=src.replace(oldLogoHtml,newLogoHtml);
const fontWait='await pg.evaluate(()=>document.fonts.ready);';
const assetWait="await pg.evaluate(()=>document.fonts.ready);await pg.waitForFunction(()=>[...document.images].every(i=>i.complete&&i.naturalWidth>0));";
if(!src.includes(fontWait)) throw new Error('J4_FONT_WAIT_ANCHOR_MISSING');
src=src.replace(fontWait,assetWait);
src=src.replace("../dist/nidom-akhlak/j4-v01","../dist/nidom-akhlak/j4-v02");
src=src.replaceAll('-v0.1.pdf','-v0.2.pdf');
console.log('QURBATA_OFFICIAL_LOGO=FROZEN_REFERENCE_DERIVATIVE_PNG');
console.log('QURBATA_LOGO_SOURCE_SHA256=4d9cd82e0f4b83aa227187005f5b71f89f7144e267fed859130fd5bef79c1f32');
eval(src);
